apiVersion: v1 
kind: ConfigMap
metadata:
  name: cfmap
data:
  DB_HOST: mysqldb
  DB_PASSWORD: User@123
  AUTH_HOST: auth
  AUTH_PORT: "8000"
  WEATHER_HOST: weather
  WEATHER_PORT: "5000"
  APIKEY: put your key here 
