apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weatherapp
    env: poc


spec: 
  replicas: 1
  selector: 
    matchLabels: 
      env: poc 
  template:
    metadata:
      name: weather-pod
      labels:
        env: poc 
    spec: 
      containers:
        - name: weather
          image: shubhamad/weather:0.0.1
          ports:
          -  name: liveness-port
             containerPort: 5000
          resources: #CHANGE
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi #256Mi        
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          env:
          - name: APIKEY 
            valueFrom:
              secretKeyRef:
                name: weatherapi
                key: apikey
---

apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  selector:
    env: poc 
  ports:
  - port: 5000
    protocol: TCP 
    targetPort: 5000

  
    